/**
 * 81 il — slug, plaka, SVG id ve bölgesel verimlilik bonusları.
 * multiplier: 1.00 = bonus yok, 1.20 = +%20 verimlilik
 *
 * Sektörler: tarim, gida, maden, petrol, metal, savunma, enerji
 */

export const REGIONS = [
  { slug: 'adana', name: 'Adana', plateCode: 1, svgPathId: 'TR-01', bonuses: [{ sector: 'tarim', multiplier: 1.15 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'adiyaman', name: 'Adıyaman', plateCode: 2, svgPathId: 'TR-02', bonuses: [{ sector: 'petrol', multiplier: 1.15 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'afyonkarahisar', name: 'Afyonkarahisar', plateCode: 3, svgPathId: 'TR-03', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'maden', multiplier: 1.08 }] },
  { slug: 'agri', name: 'Ağrı', plateCode: 4, svgPathId: 'TR-04', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.05 }] },
  { slug: 'aksaray', name: 'Aksaray', plateCode: 68, svgPathId: 'TR-68', bonuses: [{ sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'amasya', name: 'Amasya', plateCode: 5, svgPathId: 'TR-05', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.05 }] },
  { slug: 'ankara', name: 'Ankara', plateCode: 6, svgPathId: 'TR-06', bonuses: [{ sector: 'savunma', multiplier: 1.15 }, { sector: 'metal', multiplier: 1.08 }] },
  { slug: 'antalya', name: 'Antalya', plateCode: 7, svgPathId: 'TR-07', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.10 }] },
  { slug: 'ardahan', name: 'Ardahan', plateCode: 75, svgPathId: 'TR-75', bonuses: [{ sector: 'tarim', multiplier: 1.08 }, { sector: 'maden', multiplier: 1.05 }] },
  { slug: 'artvin', name: 'Artvin', plateCode: 8, svgPathId: 'TR-08', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.08 }] },
  { slug: 'aydin', name: 'Aydın', plateCode: 9, svgPathId: 'TR-09', bonuses: [{ sector: 'tarim', multiplier: 1.15 }, { sector: 'gida', multiplier: 1.10 }] },
  { slug: 'balikesir', name: 'Balıkesir', plateCode: 10, svgPathId: 'TR-10', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'maden', multiplier: 1.10 }] },
  { slug: 'bartin', name: 'Bartın', plateCode: 74, svgPathId: 'TR-74', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.05 }] },
  { slug: 'batman', name: 'Batman', plateCode: 72, svgPathId: 'TR-72', bonuses: [{ sector: 'petrol', multiplier: 1.30 }] },
  { slug: 'bayburt', name: 'Bayburt', plateCode: 69, svgPathId: 'TR-69', bonuses: [{ sector: 'maden', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.05 }] },
  { slug: 'bilecik', name: 'Bilecik', plateCode: 11, svgPathId: 'TR-11', bonuses: [{ sector: 'metal', multiplier: 1.08 }, { sector: 'tarim', multiplier: 1.05 }] },
  { slug: 'bingol', name: 'Bingöl', plateCode: 12, svgPathId: 'TR-12', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'bitlis', name: 'Bitlis', plateCode: 13, svgPathId: 'TR-13', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'bolu', name: 'Bolu', plateCode: 14, svgPathId: 'TR-14', bonuses: [{ sector: 'maden', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'burdur', name: 'Burdur', plateCode: 15, svgPathId: 'TR-15', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.05 }] },
  { slug: 'bursa', name: 'Bursa', plateCode: 16, svgPathId: 'TR-16', bonuses: [{ sector: 'savunma', multiplier: 1.18 }, { sector: 'metal', multiplier: 1.12 }] },
  { slug: 'canakkale', name: 'Çanakkale', plateCode: 17, svgPathId: 'TR-17', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'cankiri', name: 'Çankırı', plateCode: 18, svgPathId: 'TR-18', bonuses: [{ sector: 'maden', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'corum', name: 'Çorum', plateCode: 19, svgPathId: 'TR-19', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'denizli', name: 'Denizli', plateCode: 20, svgPathId: 'TR-20', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'metal', multiplier: 1.08 }] },
  { slug: 'diyarbakir', name: 'Diyarbakır', plateCode: 21, svgPathId: 'TR-21', bonuses: [{ sector: 'petrol', multiplier: 1.15 }, { sector: 'tarim', multiplier: 1.10 }] },
  { slug: 'duzce', name: 'Düzce', plateCode: 81, svgPathId: 'TR-81', bonuses: [{ sector: 'maden', multiplier: 1.10 }, { sector: 'metal', multiplier: 1.08 }] },
  { slug: 'edirne', name: 'Edirne', plateCode: 22, svgPathId: 'TR-22', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'elazig', name: 'Elazığ', plateCode: 23, svgPathId: 'TR-23', bonuses: [{ sector: 'maden', multiplier: 1.18 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'erzincan', name: 'Erzincan', plateCode: 24, svgPathId: 'TR-24', bonuses: [{ sector: 'maden', multiplier: 1.15 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'erzurum', name: 'Erzurum', plateCode: 25, svgPathId: 'TR-25', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'eskisehir', name: 'Eskişehir', plateCode: 26, svgPathId: 'TR-26', bonuses: [{ sector: 'savunma', multiplier: 1.10 }, { sector: 'metal', multiplier: 1.12 }] },
  { slug: 'gaziantep', name: 'Gaziantep', plateCode: 27, svgPathId: 'TR-27', bonuses: [{ sector: 'gida', multiplier: 1.15 }, { sector: 'savunma', multiplier: 1.08 }] },
  { slug: 'giresun', name: 'Giresun', plateCode: 28, svgPathId: 'TR-28', bonuses: [{ sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'gumushane', name: 'Gümüşhane', plateCode: 29, svgPathId: 'TR-29', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.05 }] },
  { slug: 'hakkari', name: 'Hakkari', plateCode: 30, svgPathId: 'TR-30', bonuses: [{ sector: 'maden', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.05 }] },
  { slug: 'hatay', name: 'Hatay', plateCode: 31, svgPathId: 'TR-31', bonuses: [{ sector: 'metal', multiplier: 1.15 }, { sector: 'gida', multiplier: 1.10 }] },
  { slug: 'mersin', name: 'Mersin', plateCode: 32, svgPathId: 'TR-32', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.10 }] },
  { slug: 'igdir', name: 'Iğdır', plateCode: 76, svgPathId: 'TR-76', bonuses: [{ sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'isparta', name: 'Isparta', plateCode: 33, svgPathId: 'TR-33', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'istanbul', name: 'İstanbul', plateCode: 34, svgPathId: 'TR-34', bonuses: [{ sector: 'metal', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.12 }] },
  { slug: 'izmir', name: 'İzmir', plateCode: 35, svgPathId: 'TR-35', bonuses: [{ sector: 'gida', multiplier: 1.15 }, { sector: 'tarim', multiplier: 1.10 }] },
  { slug: 'kahramanmaras', name: 'Kahramanmaraş', plateCode: 46, svgPathId: 'TR-46', bonuses: [{ sector: 'gida', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.10 }] },
  { slug: 'karabuk', name: 'Karabük', plateCode: 78, svgPathId: 'TR-78', bonuses: [{ sector: 'metal', multiplier: 1.20 }, { sector: 'maden', multiplier: 1.12 }] },
  { slug: 'karaman', name: 'Karaman', plateCode: 70, svgPathId: 'TR-70', bonuses: [{ sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'kars', name: 'Kars', plateCode: 36, svgPathId: 'TR-36', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.05 }] },
  { slug: 'kastamonu', name: 'Kastamonu', plateCode: 37, svgPathId: 'TR-37', bonuses: [{ sector: 'maden', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'kayseri', name: 'Kayseri', plateCode: 38, svgPathId: 'TR-38', bonuses: [{ sector: 'savunma', multiplier: 1.12 }, { sector: 'metal', multiplier: 1.10 }] },
  { slug: 'kilis', name: 'Kilis', plateCode: 79, svgPathId: 'TR-79', bonuses: [{ sector: 'gida', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'kirikkale', name: 'Kırıkkale', plateCode: 71, svgPathId: 'TR-71', bonuses: [{ sector: 'savunma', multiplier: 1.10 }, { sector: 'metal', multiplier: 1.08 }] },
  { slug: 'kirklareli', name: 'Kırklareli', plateCode: 39, svgPathId: 'TR-39', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.05 }] },
  { slug: 'kirsehir', name: 'Kırşehir', plateCode: 40, svgPathId: 'TR-40', bonuses: [{ sector: 'tarim', multiplier: 1.10 }] },
  { slug: 'kocaeli', name: 'Kocaeli', plateCode: 41, svgPathId: 'TR-41', bonuses: [{ sector: 'metal', multiplier: 1.18 }, { sector: 'savunma', multiplier: 1.10 }] },
  { slug: 'konya', name: 'Konya', plateCode: 42, svgPathId: 'TR-42', bonuses: [{ sector: 'tarim', multiplier: 1.20 }] },
  { slug: 'kutahya', name: 'Kütahya', plateCode: 43, svgPathId: 'TR-43', bonuses: [{ sector: 'maden', multiplier: 1.15 }, { sector: 'metal', multiplier: 1.08 }] },
  { slug: 'malatya', name: 'Malatya', plateCode: 44, svgPathId: 'TR-44', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.10 }] },
  { slug: 'manisa', name: 'Manisa', plateCode: 45, svgPathId: 'TR-45', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.10 }] },
  { slug: 'mardin', name: 'Mardin', plateCode: 47, svgPathId: 'TR-47', bonuses: [{ sector: 'petrol', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'mugla', name: 'Muğla', plateCode: 48, svgPathId: 'TR-48', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'mus', name: 'Muş', plateCode: 49, svgPathId: 'TR-49', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.08 }] },
  { slug: 'nevsehir', name: 'Nevşehir', plateCode: 50, svgPathId: 'TR-50', bonuses: [{ sector: 'tarim', multiplier: 1.08 }, { sector: 'maden', multiplier: 1.05 }] },
  { slug: 'nigde', name: 'Niğde', plateCode: 51, svgPathId: 'TR-51', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.08 }] },
  { slug: 'ordu', name: 'Ordu', plateCode: 52, svgPathId: 'TR-52', bonuses: [{ sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'osmaniye', name: 'Osmaniye', plateCode: 80, svgPathId: 'TR-80', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'rize', name: 'Rize', plateCode: 53, svgPathId: 'TR-53', bonuses: [{ sector: 'tarim', multiplier: 1.15 }] },
  { slug: 'sakarya', name: 'Sakarya', plateCode: 54, svgPathId: 'TR-54', bonuses: [{ sector: 'metal', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'samsun', name: 'Samsun', plateCode: 55, svgPathId: 'TR-55', bonuses: [{ sector: 'tarim', multiplier: 1.15 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'sanliurfa', name: 'Şanlıurfa', plateCode: 63, svgPathId: 'TR-63', bonuses: [{ sector: 'petrol', multiplier: 1.10 }, { sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'siirt', name: 'Siirt', plateCode: 56, svgPathId: 'TR-56', bonuses: [{ sector: 'petrol', multiplier: 1.15 }, { sector: 'maden', multiplier: 1.08 }] },
  { slug: 'sinop', name: 'Sinop', plateCode: 57, svgPathId: 'TR-57', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.05 }] },
  { slug: 'sirnak', name: 'Şırnak', plateCode: 73, svgPathId: 'TR-73', bonuses: [{ sector: 'petrol', multiplier: 1.25 }] },
  { slug: 'sivas', name: 'Sivas', plateCode: 58, svgPathId: 'TR-58', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.10 }] },
  { slug: 'tekirdag', name: 'Tekirdağ', plateCode: 59, svgPathId: 'TR-59', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.08 }] },
  { slug: 'tokat', name: 'Tokat', plateCode: 60, svgPathId: 'TR-60', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'gida', multiplier: 1.05 }] },
  { slug: 'trabzon', name: 'Trabzon', plateCode: 61, svgPathId: 'TR-61', bonuses: [{ sector: 'tarim', multiplier: 1.12 }, { sector: 'maden', multiplier: 1.05 }] },
  { slug: 'tunceli', name: 'Tunceli', plateCode: 62, svgPathId: 'TR-62', bonuses: [{ sector: 'maden', multiplier: 1.15 }, { sector: 'enerji', multiplier: 1.10 }] },
  { slug: 'usak', name: 'Uşak', plateCode: 64, svgPathId: 'TR-64', bonuses: [{ sector: 'maden', multiplier: 1.12 }, { sector: 'tarim', multiplier: 1.08 }] },
  { slug: 'van', name: 'Van', plateCode: 65, svgPathId: 'TR-65', bonuses: [{ sector: 'tarim', multiplier: 1.10 }, { sector: 'maden', multiplier: 1.08 }] },
  { slug: 'yalova', name: 'Yalova', plateCode: 77, svgPathId: 'TR-77', bonuses: [{ sector: 'metal', multiplier: 1.10 }, { sector: 'savunma', multiplier: 1.05 }] },
  { slug: 'yozgat', name: 'Yozgat', plateCode: 66, svgPathId: 'TR-66', bonuses: [{ sector: 'tarim', multiplier: 1.12 }] },
  { slug: 'zonguldak', name: 'Zonguldak', plateCode: 67, svgPathId: 'TR-67', bonuses: [{ sector: 'maden', multiplier: 1.25 }, { sector: 'enerji', multiplier: 1.12 }] },
];

export const FACTORY_TYPES = [
  { code: 'tarla', sector: 'tarim', name: 'Tarla', buildCost: 5000, buildDurationSec: 3600, dailyMaintenance: 100, maxWorkers: 10, storageCapacity: 500 },
  { code: 'gida_fabrikasi', sector: 'gida', name: 'Gıda Fabrikası', buildCost: 15000, buildDurationSec: 7200, dailyMaintenance: 300, maxWorkers: 15, storageCapacity: 300 },
  { code: 'maden_ocagi', sector: 'maden', name: 'Maden Ocağı', buildCost: 25000, buildDurationSec: 10800, dailyMaintenance: 500, maxWorkers: 15, storageCapacity: 400 },
  { code: 'demir_celik_fabrikasi', sector: 'metal', name: 'Demir-Çelik Fabrikası', buildCost: 60000, buildDurationSec: 21600, dailyMaintenance: 1500, maxWorkers: 20, storageCapacity: 350 },
  { code: 'petrol_kuyusu', sector: 'petrol', name: 'Petrol Kuyusu', buildCost: 50000, buildDurationSec: 14400, dailyMaintenance: 1000, maxWorkers: 20, storageCapacity: 200 },
  { code: 'petrol_rafinerisi', sector: 'petrol', name: 'Petrol Rafinerisi', buildCost: 80000, buildDurationSec: 21600, dailyMaintenance: 2000, maxWorkers: 25, storageCapacity: 150 },
  { code: 'silah_fabrikasi', sector: 'savunma', name: 'Silah Fabrikası', buildCost: 45000, buildDurationSec: 18000, dailyMaintenance: 800, maxWorkers: 18, storageCapacity: 200 },
  { code: 'elektrik_santrali', sector: 'enerji', name: 'Elektrik Santrali', buildCost: 100000, buildDurationSec: 28800, dailyMaintenance: 3000, maxWorkers: 30, storageCapacity: 0 },
];

export const ITEMS = [
  { code: 'bugday', name: 'Buğday', sector: 'tarim', basePrice: 10, weaponPower: 0 },
  { code: 'misir', name: 'Mısır', sector: 'tarim', basePrice: 8, weaponPower: 0 },
  { code: 'pamuk', name: 'Pamuk', sector: 'tarim', basePrice: 15, weaponPower: 0 },
  { code: 'un', name: 'Un', sector: 'gida', basePrice: 25, weaponPower: 0 },
  { code: 'ekmek', name: 'Ekmek', sector: 'gida', basePrice: 40, weaponPower: 0 },
  { code: 'komur', name: 'Kömür', sector: 'maden', basePrice: 30, weaponPower: 0 },
  { code: 'demir_cevheri', name: 'Demir Cevheri', sector: 'maden', basePrice: 45, weaponPower: 0 },
  { code: 'celik', name: 'Çelik', sector: 'metal', basePrice: 120, weaponPower: 0 },
  { code: 'ham_petrol', name: 'Ham Petrol', sector: 'petrol', basePrice: 50, weaponPower: 0 },
  { code: 'benzin', name: 'Benzin', sector: 'petrol', basePrice: 80, weaponPower: 0 },
  { code: 'elektrik', name: 'Elektrik', sector: 'enerji', basePrice: 20, weaponPower: 0 },
  { code: 'hafif_silah', name: 'Hafif Silah', sector: 'savunma', basePrice: 200, weaponPower: 5, stackMax: 100 },
  { code: 'tifek', name: 'Tüfek', sector: 'savunma', basePrice: 500, weaponPower: 15, stackMax: 50 },
  { code: 'agir_silah', name: 'Ağır Silah', sector: 'savunma', basePrice: 1200, weaponPower: 30, stackMax: 20 },
  { code: 'cephane', name: 'Cephane', sector: 'savunma', basePrice: 60, weaponPower: 0, stackMax: 500 },
];
